---
env:
  contexts:
  - name: "Trillium UAT"
    urls: "https://trilliumcctuat.ltfs.com/TrilliumCCTWeb/login.html"
    includePaths: "https://trilliumcctuat.ltfs.com/.*"
    excludePaths: []
    authentication:
        method: "form"
        parameters:
          loginPageUrl: "https://trilliumcctuat.ltfs.com/TrilliumCCTWeb/login.html"
          loginRequestUrl: "https://trilliumcctuat.ltfs.com/TrilliumCCTWeb/login.html"
          loginRequestBody: "username=50053550&password=Intermiami@1998"
        verification:
          method: "response"
          loggedInRegex: "Logout"
          loggedOutRegex: "Login"
          pollFrequency: 60
          pollUnits: "requests"
          pollUrl: ""
          pollPostData: ""
    #   authentication:
    #   method: "form"
    #   parameters: {}
    #   verification:
    #   method: "form"
    #   pollFrequency: 60
    #   pollUnits: "requests"
    sessionManagement:
      method: "cookie"
      parameters: {}
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    scanOnlyInScope: true
    enableTags: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
- parameters: {}
  name: "spider"
  type: "spider"
- parameters:
    maxDuration: 60
    maxCrawlDepth: 10
    numberOfBrowsers: 1
  name: "spiderAjax"
  type: "spiderAjax"
- parameters: {}
  name: "passiveScan-wait"
  type: "passiveScan-wait"
- parameters: {}
  policyDefinition:
    rules: []
  name: "activeScan"
  type: "activeScan"
- parameters:
    template: "traditional-json-plus"
    reportDir: "C:\My\AppScan\CheckmarxOne_DAST"
    reportTitle: "Trillium UAT CxOne Scanning Report"
    reportDescription: ""
  name: "report"
  type: "report"

