name: DAST Demo

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  dast:
    runs-on: ubuntu-latest
    name: DAST on Prem Testing Action
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Create Output folder
        run: mkdir ${{ github.workspace }}/output_fold
      - name: Change dir owner
        run: sudo chown -R 1000:1000 ${{ github.workspace }}
      - name: Checkmarx DAST Github Action
        uses: Checkmarx/dast-github-action@v1.0.6
        env:
          CX_APIKEY: ${{ secrets.CxOne_Api }}
        with:
          command: web
          config: dast-config/zap_config.yaml
          environment_id: 93dc4f36-20ca-4282-b832-7ce5a1d49f84
          fail_on: "HIGH"
          log_level: info
          base_url: https://eu.ast.checkmarx.net/
          verbose: true
          timeout: 100000
          output: ${{ github.workspace }}/output_fold
